# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Skizze.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(537, 462)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.titelLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(36)
        self.titelLabel.setFont(font)
        self.titelLabel.setObjectName(_fromUtf8("titelLabel"))
        self.verticalLayout_3.addWidget(self.titelLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.datenButton = QtGui.QPushButton(self.centralwidget)
        self.datenButton.setObjectName(_fromUtf8("datenButton"))
        self.verticalLayout.addWidget(self.datenButton)
        self.uebersichtButton = QtGui.QPushButton(self.centralwidget)
        self.uebersichtButton.setObjectName(_fromUtf8("uebersichtButton"))
        self.verticalLayout.addWidget(self.uebersichtButton)
        self.kennzahlenButton = QtGui.QPushButton(self.centralwidget)
        self.kennzahlenButton.setObjectName(_fromUtf8("kennzahlenButton"))
        self.verticalLayout.addWidget(self.kennzahlenButton)
        self.quellenButton = QtGui.QPushButton(self.centralwidget)
        self.quellenButton.setObjectName(_fromUtf8("quellenButton"))
        self.verticalLayout.addWidget(self.quellenButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.kantoneLabel = QtGui.QLabel(self.centralwidget)
        self.kantoneLabel.setObjectName(_fromUtf8("kantoneLabel"))
        self.gridLayout.addWidget(self.kantoneLabel, 0, 0, 1, 1)
        self.kantoneBox = QtGui.QComboBox(self.centralwidget)
        self.kantoneBox.setObjectName(_fromUtf8("kantoneBox"))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.setItemText(0, _fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.kantoneBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.kantoneBox, 0, 1, 1, 1)
        self.kantoneLabel_2 = QtGui.QLabel(self.centralwidget)
        self.kantoneLabel_2.setObjectName(_fromUtf8("kantoneLabel_2"))
        self.gridLayout.addWidget(self.kantoneLabel_2, 1, 0, 1, 1)
        self.kantoneBox_2 = QtGui.QComboBox(self.centralwidget)
        self.kantoneBox_2.setObjectName(_fromUtf8("kantoneBox_2"))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.setItemText(0, _fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.kantoneBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.kantoneBox_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.plotButton = QtGui.QPushButton(self.centralwidget)
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.verticalLayout_3.addWidget(self.plotButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExtras = QtGui.QAction(MainWindow)
        self.actionExtras.setObjectName(_fromUtf8("actionExtras"))
        self.menuMen.addAction(self.actionExtras)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.titelLabel.setText(_translate("MainWindow", "Zu- und Wegzüge Stadt Zürich", None))
        self.datenButton.setToolTip(_translate("MainWindow", "Daten aus dem Internet laden", None))
        self.datenButton.setText(_translate("MainWindow", "Daten laden", None))
        self.uebersichtButton.setToolTip(_translate("MainWindow", "sämtliche Zu- und Wegzüge seit 1993", None))
        self.uebersichtButton.setText(_translate("MainWindow", "Gesamtübersicht", None))
        self.kennzahlenButton.setToolTip(_translate("MainWindow", "diverse Kennzahlen", None))
        self.kennzahlenButton.setText(_translate("MainWindow", "Kennzahlen", None))
        self.quellenButton.setToolTip(_translate("MainWindow", "Quellenverzeichnis", None))
        self.quellenButton.setText(_translate("MainWindow", "Quellen", None))
        self.kantoneLabel.setText(_translate("MainWindow", "nach Kanton:", None))
        self.kantoneBox.setToolTip(_translate("MainWindow", "Kantonauswahl", None))
        self.kantoneBox.setItemText(1, _translate("MainWindow", "Aargau", None))
        self.kantoneBox.setItemText(2, _translate("MainWindow", "Appenzell Ausserrhoden", None))
        self.kantoneBox.setItemText(3, _translate("MainWindow", "Appenzell Innerrhoden", None))
        self.kantoneBox.setItemText(4, _translate("MainWindow", "Ausland", None))
        self.kantoneBox.setItemText(5, _translate("MainWindow", "Basel-Landschaft", None))
        self.kantoneBox.setItemText(6, _translate("MainWindow", "Basel-Stadt", None))
        self.kantoneBox.setItemText(7, _translate("MainWindow", "Bern / Berne", None))
        self.kantoneBox.setItemText(8, _translate("MainWindow", "Fribourg / Freiburg", None))
        self.kantoneBox.setItemText(9, _translate("MainWindow", "Genève", None))
        self.kantoneBox.setItemText(10, _translate("MainWindow", "Glarus", None))
        self.kantoneBox.setItemText(11, _translate("MainWindow", "Graubünden / Grigioni / Grischun", None))
        self.kantoneBox.setItemText(12, _translate("MainWindow", "Jura", None))
        self.kantoneBox.setItemText(13, _translate("MainWindow", "Luzern", None))
        self.kantoneBox.setItemText(14, _translate("MainWindow", "Neuchâtel", None))
        self.kantoneBox.setItemText(15, _translate("MainWindow", "Nidwalden", None))
        self.kantoneBox.setItemText(16, _translate("MainWindow", "Obwalden", None))
        self.kantoneBox.setItemText(17, _translate("MainWindow", "Schaffhausen", None))
        self.kantoneBox.setItemText(18, _translate("MainWindow", "Schweiz Unbekannt", None))
        self.kantoneBox.setItemText(19, _translate("MainWindow", "Schwyz", None))
        self.kantoneBox.setItemText(20, _translate("MainWindow", "Solothurn", None))
        self.kantoneBox.setItemText(21, _translate("MainWindow", "St. Gallen", None))
        self.kantoneBox.setItemText(22, _translate("MainWindow", "Thurgau", None))
        self.kantoneBox.setItemText(23, _translate("MainWindow", "Ticino", None))
        self.kantoneBox.setItemText(24, _translate("MainWindow", "Unbekannt", None))
        self.kantoneBox.setItemText(25, _translate("MainWindow", "Uri", None))
        self.kantoneBox.setItemText(26, _translate("MainWindow", "Valais / Wallis", None))
        self.kantoneBox.setItemText(27, _translate("MainWindow", "Vaud", None))
        self.kantoneBox.setItemText(28, _translate("MainWindow", "Zug", None))
        self.kantoneBox.setItemText(29, _translate("MainWindow", "Zürich", None))
        self.kantoneLabel_2.setText(_translate("MainWindow", "Jahr:", None))
        self.kantoneBox_2.setToolTip(_translate("MainWindow", "Jahr auswählen", None))
        self.kantoneBox_2.setItemText(1, _translate("MainWindow", "1993", None))
        self.kantoneBox_2.setItemText(2, _translate("MainWindow", "1994", None))
        self.kantoneBox_2.setItemText(3, _translate("MainWindow", "1995", None))
        self.kantoneBox_2.setItemText(4, _translate("MainWindow", "1996", None))
        self.kantoneBox_2.setItemText(5, _translate("MainWindow", "1997", None))
        self.kantoneBox_2.setItemText(6, _translate("MainWindow", "1998", None))
        self.kantoneBox_2.setItemText(7, _translate("MainWindow", "1999", None))
        self.kantoneBox_2.setItemText(8, _translate("MainWindow", "2000", None))
        self.kantoneBox_2.setItemText(9, _translate("MainWindow", "2001", None))
        self.kantoneBox_2.setItemText(10, _translate("MainWindow", "2002", None))
        self.kantoneBox_2.setItemText(11, _translate("MainWindow", "2003", None))
        self.kantoneBox_2.setItemText(12, _translate("MainWindow", "2004", None))
        self.kantoneBox_2.setItemText(13, _translate("MainWindow", "2005", None))
        self.kantoneBox_2.setItemText(14, _translate("MainWindow", "2006", None))
        self.kantoneBox_2.setItemText(15, _translate("MainWindow", "2007", None))
        self.kantoneBox_2.setItemText(16, _translate("MainWindow", "2008", None))
        self.kantoneBox_2.setItemText(17, _translate("MainWindow", "2009", None))
        self.kantoneBox_2.setItemText(18, _translate("MainWindow", "2010", None))
        self.kantoneBox_2.setItemText(19, _translate("MainWindow", "2011", None))
        self.kantoneBox_2.setItemText(20, _translate("MainWindow", "2012", None))
        self.kantoneBox_2.setItemText(21, _translate("MainWindow", "2013", None))
        self.kantoneBox_2.setItemText(22, _translate("MainWindow", "2014", None))
        self.kantoneBox_2.setItemText(23, _translate("MainWindow", "2015", None))
        self.plotButton.setToolTip(_translate("MainWindow", "Grafik anzeigen lassen", None))
        self.plotButton.setText(_translate("MainWindow", "Plot Anzeigen", None))
        self.label.setText(_translate("MainWindow", "Statistics Application IT PROG 2, R. Hofstetter, J. Friedrich", None))
        self.menuMen.setTitle(_translate("MainWindow", "Menü", None))
        self.actionExtras.setText(_translate("MainWindow", "Extras", None))

